### ISSUE TITLE
是否用PHP自带的防注入会比较好呢？

### ISSUE THREAD

**Issue by big-dream** [likeyun/liKeYun_Dwz#5]
使用中，发现生成的短链如果带有LF字符，则会被过滤，导致链接不存在。经过[查阅代码](https://github.com/likeyun/liKeYun_Dwz/blob/d8ea04e91ed54cc53f997e0ecfbbec4a2a556700/index.php#L37)，是SQL防注入函数过滤掉了。
替换成使用`mysqli::escape_string()`后，功能正常。
对此有个疑问，是否用PHP自带的防注入函数`mysqli::escape_string()`会比较好呢？
当时没使用`mysqli::escape_string()`是出于什么考虑呢？
感谢赐教

**Comment by likeyun** [comment]
下个版本将使用PDO代替mySqli

--------------原始邮件--------------
发件人："蒋文健 ***@***.***&gt;;
发送时间：2022年5月10日(星期二) 上午9:19
收件人："likeyun/liKeYun_Dwz" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[likeyun/liKeYun_Dwz] 是否用PHP自带的防注入会比较好呢？ (Issue #5)
-----------------------------------

 

 
使用中，发现生成的短链如果带有LF字符，则会被过滤，导致链接不存在。经过查阅代码，是SQL防注入函数过滤掉了。
 替换成使用mysqli::escape_string()后，功能正常。
 对此有个疑问，是否用PHP自带的防注入函数mysqli::escape_string()会比较好呢？
 当时没使用mysqli::escape_string()是出于什么考虑呢？
 感谢赐教

**Comment by big-dream** [comment]
好的，了解👍
